language: python

sudo: false

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

env:
  - DJANGO="Django>=1.9,<1.10"
  - DJANGO="Django>=1.10,<1.11"
  - DJANGO="Django>=1.11,<1.12"

install:
  - pip install -U coverage codecov
  - pip install -U $DJANGO
  - pip freeze

script: coverage run setup.py test

after_success: codecov
