language: python

sudo: false

python:
  - 2.7
  - 3.2
  - 3.3

env:
  - DJANGO="Django>=1.4,<1.5"
  - DJANGO="Django>=1.6,<1.7"
  - DJANGO="Django>=1.7,<1.8"
  - DJANGO="Django>=1.8,<1.9"
  - DJANGO="Django>=1.9a,<1.10"

install:
  - pip install -U 'coverage<4' codecov
  - pip install -U $DJANGO
  - python -c 'from __future__ import print_function; import django; print("Django " + django.get_version())'

script: coverage run setup.py test

matrix:
  exclude:
   - python: 3.2
     env: DJANGO="Django>=1.4,<1.5"
   - python: 3.3
     env: DJANGO="Django>=1.4,<1.5"
   - python: 3.2
     env: DJANGO="Django>=1.9a,<1.10"
   - python: 3.3
     env: DJANGO="Django>=1.9a,<1.10"

  include:
   - python: 2.6
     env: DJANGO="Django>=1.4,<1.5"
   - python: 3.4
     env: DJANGO="Django>=1.7,<1.8"
   - python: 3.4
     env: DJANGO="Django>=1.8,<1.9"
   - python: 3.5
     env: DJANGO="Django>=1.8,<1.9"
   - python: 3.5
     env: DJANGO="Django>=1.9,<1.10"

after_success: codecov
